[project.base]
author = "untodesu"
about = "VHS.V7 filter"
input_mode = "disabled"
output_mode = "disabled"
output_resolution = [640, 480]
final_pass = "final_rgb"

# Special template for displaying SMPTE test pattern
# Run RITEG with the following command line to execute:
#   riteg -project project/vhs -preset SMPTE
[project.SMPTE]
input_mode = "oneshot"
input_path = "cwd:media/vhs43.01.png"

# Special template for displaying PM5544 test pattern
# Run RITEG with the following command line to execute:
#   riteg -project project/vhs -preset PM5544
[project.PM5544]
input_mode = "oneshot"
input_path = "cwd:media/vhs43.02.png"

# Special template for displaying a blank test image
# Run RITEG with the following command line to execute:
#   riteg -project project/vhs -preset TESTCARD
[project.TESTCARD]
input_mode = "oneshot"
input_path = "cwd:media/vhs43.03.png"

# Special template for bulk-processing
# 4:3 example images; run RITEG with the
# following command line to execute:
#   riteg -project project/vhs -preset docs43
[project.docs43]
input_mode = "sprintf"
input_format = "cwd:media/vhs43.%02d.png"
input_maxframes = "probe"   # load until first failure
output_mode = "sprintf"
output_format = "cwd:docs/project.vhs43.%02d.png"
output_maxframes = "input"  # save until input stops loading
output_filetype = "guess"   # try to figure it out from output_format

# Special template for bulk-processing
# 16:9 example images; run RITEG with the
# following command line to execute:
#   riteg -project project/vhs -preset docs169
[project.docs169]
input_mode = "sprintf"
input_format = "cwd:media/vhs169.%02d.png"
input_maxframes = "probe"   # load until first failure
output_mode = "sprintf"
output_format = "cwd:docs/project.vhs169.%02d.png"
output_maxframes = "input"  # save until input stops loading
output_filetype = "guess"   # try to figure it out from output_format
output_resolution = [848, 480]

[project.custom]
input_mode = "sprintf"
input_format = "cwd:frames_in/%04d.png"
input_maxframes = "probe"
output_mode = "sprintf"
output_format = "cwd:frames_out/%04d.jpg"
output_maxframes = "input"
output_filetype = "guess"
output_jpeg_quality = 95

[[shader_pass]]
name = "gamma_correct"
shader = "project:shaders/gamma_correct.frag"
channels = ["!image"]
parameters = [0.9]
scale = [1.0, 0.5]

[[shader_pass]]
name = "vhs_cutoff"
shader = "project:shaders/vhs_cutoff.frag"
channels = ["gamma_correct"]
parameters = [0.01]
scale = [1.0, 0.5]

[[shader_pass]]
name = "base_yiq"
shader = "project:shaders/rgb_to_yiq.frag"
channels = ["vhs_cutoff"]
scale = [1.0, 0.5]

[[shader_pass]]
name = "luminance_lp_a"
shader = "project:shaders/blur_lowpass.frag"
channels = ["base_yiq"]
parameters = [64.0, 0.285, 1.0]
scale = [1.0, 0.5]

[[shader_pass]]
name = "luminance_lp_b"
shader = "project:shaders/blur_gaussian_9.frag"
channels = ["luminance_lp_a"]
parameters = [4.0, 0.0]
scale = [1.0, 0.5]

[[shader_pass]]
name = "luminance"
shader = "project:shaders/subtract.frag"
channels = ["luminance_lp_a", "luminance_lp_b"]
parameters = [2.0, 1.0]
scale = [1.0, 0.5]

[[shader_pass]]
name = "vhs_color_noise"
shader = "project:shaders/vhs_color_noise.frag"
channels = ["base_yiq"]
parameters = [0.03125, 0.05, 50.0, 0.02]
scale = [1.0, 0.5]

[[shader_pass]]
name = "chrominance_lp"
shader = "project:shaders/blur_lowpass.frag"
channels = ["base_yiq"]
parameters = [128.0, 0.025, 1.0]
scale = [1.0, 0.5]

[[shader_pass]]
name = "vhs_color_amplify"
shader = "project:shaders/vhs_color_amplify.frag"
channels = ["chrominance_lp"]
parameters = [0.75, 0.1, 1.0]
scale = [1.0, 0.5]

[[shader_pass]]
name = "yiq_swizzle"
shader = "project:shaders/yiq_swizzle.frag"
channels = ["luminance", "vhs_color_amplify"]
scale = [1.0, 0.5]

[[shader_pass]]
name = "vhs_dropout"
shader = "project:shaders/vhs_dropout.frag"
channels = ["yiq_swizzle"]
parameters = [0.9999999, 0.000001, 50.0, 48.0, 0.999999]
scale = [1.0, 0.5]

[[shader_pass]]
name = "ntsc_modulate"
shader = "project:shaders/ntsc_modulate.frag"
channels = ["vhs_dropout"]

[[shader_pass]]
name = "ntsc_snow"
shader = "project:shaders/ntsc_snow.frag"
channels = ["ntsc_modulate"]
parameters = [0.25, 0.0625]

[[shader_pass]]
name = "ntsc_demodulate"
shader = "project:shaders/ntsc_demodulate.frag"
channels = ["ntsc_snow"]

[[shader_pass]]
name = "ntsc_postprocess"
shader = "project:shaders/ntsc_postprocess.frag"
channels = ["ntsc_demodulate"]
parameters = [1.0, 3.5, 150]

[[shader_pass]]
name = "vhs_headswitch"
shader = "project:shaders/vhs_headswitch.frag"
channels = ["ntsc_postprocess"]
parameters = [0.003125, 30.0, 3.0, 0.0625]
scale = [1.0, 0.5]

[[shader_pass]]
name = "vhs_tracking"
shader = "project:shaders/vhs_tracking.frag"
channels = ["vhs_headswitch"]
parameters = [70.0, 2.0, 0.0625]
scale = [1.0, 0.5]

[[shader_pass]]
name = "final_rgb"
shader = "project:shaders/yiq_to_rgb.frag"
channels = ["vhs_tracking"]
scale = [1.0, 0.5]
