name: Documentation SSG
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - docs/**
      - mkdocs.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.GITHUB_SHA }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.GITHUB_SHA }}
          lfs: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install MkDocs and MkDocs-Material
        run: python -m pip install mkdocs mkdocs-material
      - name: Generate static HTML
        run: mkdocs build --site-dir build/www
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/www
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          id: deployment
